# Generated by Django 5.0.2 on 2024-02-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Emp_code', models.CharField(max_length=5)),
                ('MobileNumber', models.CharField(max_length=20)),
                ('Position', models.CharField(max_length=50)),
            ],
        ),
    ]
